version: '3.8'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 80s

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 80s

  pricing-analytics:
    build: .
    ports:
      - "8001:8001"
    volumes:      
      - ./bash_scripts:/usr/src/app/bash_scripts
      - ./config:/usr/src/app/config
      - ./migrations:/usr/src/app/migrations
    environment:      
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    healthcheck:
      test: ["CMD", "bash", "bash_scripts/healthcheck.sh"]
      interval: 2m
      timeout: 1m30s
      retries: 5
      start_period: 2m
      
volumes:
  data:
