version: '3.8'

services:     
  pricing-analytics:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
    environment:      
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
    healthcheck:
      test: ["CMD", "bash", "bash_scripts/healthcheck.sh"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 80s      

volumes:
  data:
