"""add marketplace info to research process

Revision ID: 22cde968779f
Revises: ffe44f575623
Create Date: 2024-04-18 00:45:44.576830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cde968779f'
down_revision: Union[str, None] = 'ffe44f575623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_research', sa.Column('marketplace_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_research', 'marketplace_id')
    # ### end Alembic commands ###
