"""Initial migration

Revision ID: 33e74cd01142
Revises: 
Create Date: 2024-04-12 00:33:38.335613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e74cd01142'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_research',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('sellers', sa.JSON(), nullable=True),
    sa.Column('conducted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_research_id'), 'pricing_research', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_research_sku'), 'pricing_research', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_research_sku'), table_name='pricing_research')
    op.drop_index(op.f('ix_pricing_research_id'), table_name='pricing_research')
    op.drop_table('pricing_research')
    # ### end Alembic commands ###
