"""Initial migration

Revision ID: 55d959ca5aae
Revises:
Create Date: 2024-04-18 15:34:08.784392
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '55d959ca5aae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pricing_research',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('marketplace', sa.String(length=255), nullable=True),
        sa.Column('sku', sa.String(length=255), nullable=True),
        sa.Column('marketplace_id', sa.String(length=255), nullable=True),
        sa.Column('description', sa.String(length=1024), nullable=True),
        sa.Column('brand', sa.String(length=255), nullable=True),
        sa.Column('category', sa.String(length=255), nullable=True),
        sa.Column('url', sa.String(length=512), nullable=True),
        sa.Column('strategy', sa.String(length=255), nullable=True),
        sa.Column('sellers', sa.JSON(), nullable=True),
        sa.Column('conducted_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_pricing_research_id'),
        'pricing_research',
        ['id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_pricing_research_sku'),
        'pricing_research',
        ['sku'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_pricing_research_sku'), table_name='pricing_research'
    )
    op.drop_index(
        op.f('ix_pricing_research_id'), table_name='pricing_research'
    )
    op.drop_table('pricing_research')
    # ### end Alembic commands ###
