name: Docker Compose Test

on:
  workflow_run:
    workflows: ["Source Code Test"] 
    branches: [master]
    types:
      - completed

jobs:
  docker-compose-up:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set storage mode to SQLite
        run: echo -e "[storage]\nmode=0" > config/storage.cfg
      - name: Build and Start the Docker containers
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=0" >> .env
          docker-compose up --build -d
      - name: Check if container is healthy
        run: |
          sleep 90          
          health_status=$(docker inspect --format='{{.State.Health.Status}}' $(docker-compose ps -q pricing-analytics))
          max_attempts=50
          while [ $health_status != "healthy" ]; do
            health_status=$(docker inspect --format='{{.State.Health.Status}}' $(docker-compose ps -q pricing-analytics))
            echo "Attempt $attempt: Container Health Status - $health_status"
            if [ "$max_attempts" -eq "$attempt" ]; then
              echo "Container not healthy after $max_attempts attempts."
              exit 1
            fi
            attempt=$((attempt + 1))
            sleep 1
          done
                
      - name: Test /api/docs endpoint
        run: |
          curl -s http://0.0.0.0:8001/api/docs > /dev/null || exit 1
      - name: Shut down the Docker containers
        run: docker-compose down
