name: Integration Test

on:
  workflow_run:
    workflows: ["Docker Compose Test"]
    branches: [master]
    types:
      - completed
  
jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Compose
      run: |
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_HOST=localhost" >> .env
        echo "DB_PORT=5432" >> .env

    - name: Build and start Docker containers
      run: docker-compose up -d web

    - name: Wait for FastAPI to become available
      run: |
        until $(curl --output /dev/null --silent --head --fail http://localhost:8001/api/docs); do
          printf '.'
          sleep 5
        done

    - name: Run Integration Tests
      env:
        VALID_PRODUCT_URL: ${{ secrets.VALID_PRODUCT_URL }}
      run: |
        # Example POST request to the /research endpoint
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST http://0.0.0.0:8001/api/research -H "Content-Type: application/json" -d '{"product_url": "${VALID_PRODUCT_URL}", "research_strategy": 0}')
        if [ "$RESPONSE" -ne "200" ]; then
          echo "Integration test failed: Response code $RESPONSE"
          exit 1
        fi

    - name: Cleanup
      run: docker-compose down

volumes:
  postgres_data: