name: PostgreSQL Integration Test

on:
  workflow_run:
    workflows: ["Docker Compose Test"]
    branches: [master]
    types:
      - completed

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set storage mode to PostgreSQL
        run: echo -e "[storage]\nmode=1" > config/settings.cfg

      - name: Build and Start the Docker containers
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=postgres" >> .env
          echo "DB_PORT=5432" >> .env
          docker-compose up --build -d

      - name: Check if container is healthy
        run: |
          sleep 90
          docker-compose logs --tail 100
         

      - name: Test /api/docs endpoint
        run: |
          curl -s http://0.0.0.0:8001/api/docs > /dev/null || exit 1

      - name: Shut down the Docker containers
        run: docker-compose down
