name: Docker Compose Test

on:
  workflow_run:
    workflows: ["Source Code Test"] 
    branches: [master]
    types:
      - completed

jobs:
  docker-compose-up:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set storage mode to SQLite
        run: echo -e "[storage]\nmode=0" > config/settings.cfg
      
      - name: Build and Start the Docker containers
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=0" >> .env
          docker-compose up --build -d
      
      - name: Check if container is healthy
        run: |
          sleep 90
          attempt=1
          container_id=$(docker-compose ps -q pricing-analytics)
          health_status=$(docker inspect --format='{{.State.Health.Status}}' $container_id)
          while [ "$health_status" != "healthy" ]; do
            echo "Attempt $attempt: Container Health Status - $health_status"
            echo "Logs from the container:"
            docker logs $container_id
            if [ $attempt -ge 20 ]; then
              echo "Container not healthy after 20 attempts."
              exit 1
            fi
            sleep 2
            health_status=$(docker inspect --format='{{.State.Health.Status}}' $container_id)
            attempt=$((attempt + 1))
          done
          echo "Container is now healthy."
                
      - name: Test /api/docs endpoint
        run: |
          curl -s http://0.0.0.0:8001/api/docs > /dev/null || exit 1
      - name: Shut down the Docker containers
        run: docker-compose down
